name: Docker Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: ~/.docker/cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker images
        run: |
          docker build -t flask-app -f Dockerfile .
          docker build -t dashboard -f Dockerfile .
          docker build -t mlflow -f Dockerfile .

      - name: Run tests
        run: docker run --rm flask-app

      - name: Save Docker images
        run: |
          docker save flask-app -o flask-app.tar
          docker save dashboard -o dashboard.tar
          docker save mlflow -o mlflow.tar

      - name: Upload Docker images artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flask-app
          path: flask-app.tar
        with:
          name: dashboard
          path: dashboard.tar
        with:
          name: mlflow
          path: mlflow.tar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Docker images artifacts
        uses: actions/download-artifact@v3
        with:
          name: flask-app
          name: dashboard
          name: mlflow

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Load Docker images
        run: |
          docker load -i flask-app.tar
          docker load -i dashboard.tar
          docker load -i mlflow.tar

      - name: Tag Docker images
        run: |
          docker tag flask-app ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker tag dashboard ${{ secrets.DOCKER_USERNAME }}/dashboard:latest
          docker tag mlflow ${{ secrets.DOCKER_USERNAME }}/mlflow:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/dashboard:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/mlflow:latest
